README.md
I have updated the `git-lfs` link. However, we will probably be moving away from `git-lfs` to AWS S3 or something similar.
Signed-off-by: Gaurav Gahlot <gaurav.gahlot19@gmail.com>
=> Updated git-lfs instructions link for Linux users

dhcp.go, installers/osie/main.go, installers/osie/mirror.go, job/helpers.go, packet/models.go
At present, the default action is `install`. Therefore, for the time being, a user must set the `allow_workflow: true` to bootstrap a worker in workflow mode.
In the near future, this will not be required as every worker will by default boot into a workflow.
=> Support for workflow mode

.drone.yml, files/ignition/networkd.go, files/ignition/systemd.go, http.go, installers/coreos/installer_test.go, installers/coreos/main_test.go, installers/custom_ipxe/main_test.go, installers/nixos/main.go, installers/nixos/main_test.go, installers/osie/main_test.go, installers/rancher/main_test.go, installers/vmware/kickstart-esxi.go, installers/vmware/kickstart_script_test.go, installers/vmware/main_test.go, ipxe/dhcp_options.go, job/dhcp.go, job/dhcp_test.go, job/events.go, job/ipxe.go, job/job.go, job/job_test.go, job/mock.go, main.go, packet/client.go, syslog/receiver.go, tftp.go, tftp/tftp.go
And fix CI test for it. goimports is no longer installed by default, we
didn't catch it because of the `|` and not having `set -u pipefail`
=> Fix imports sort order

installers/vmware/kickstart-esxi.go, installers/vmware/kickstart_script_test.go, installers/vmware/main.go
The purpose of this pull request is to add initial supportfor ESXi 7.0 in the boots vmware installer.
=> Add VMware ESXi 7.0

installers/vmware/kickstart-esxi.go, installers/vmware/kickstart_script_test.go, installers/vmware/testdata/vmware_base.txt
Previously the tink_host function pointed to conf.PublicIPv4 which doesn't
work well for virtual host based http servers, as the Host header being
passed was the IP rather than a domain name.
This is resolved by using conf.PublicFQDN which, if the PUBLIC_FQDN
environment variable is not set, falls back to conf.PublicIPv4 but allows
the administrator to set the PUBLIC_FQDN environment variable to override
this with a domain name. ex: boots.example.com
=> switch to using conf.PublicFQDN for tink_host to resolve phone-home issues

conf/config.go, installers/osie/main.go
To enable eclypsium scanning/registration during deprovision but not expose the
token in git we allow the token to be set during run time via an environment
variable and then pass the token into osie during boot.
* add ECLYPSIUM_TOKEN environment variable
* supply eclypsium_token kernel param during osie if defined
=> Add ECLYPSIUM_TOKEN environment variable | ENG-5336

installers/osie/main.go
No need to pass the token into osie, and risk possible exposure, when it's not needed.   Since it's only needed during deprovision, we only pass it then.
=> Only pass eclypsium_token to osie during deprovisioning | ENG-4970

installers/vmware/kickstart-esxi.go
This is to add better VMware support for both the c3.medium and c3.small server types. The storage driver which sets the installation disk is handled by the --firstdisk config directive.
=> Add c3.medium and c3.small firstdisk for VMware

installers/vmware/kickstart-esxi.go
This is to add logic around the firstdisk config option, specifically for the v1 plan version of c3.medium.
=> Set different firstdisk on c3.medium.x86.01 plan version

installers/osie/main.go, job/helpers.go, job/mock.go, packet/models.go, packet/models_test.go
This lets us specify a custom osie version (for testing, yay testing) by supplying the info at provision time, via userdata. I've set it up so that when API has support for this in the provision call it should work already.
=> Custom osie via userdata

job/dhcp.go
this error was printed if a dhcp packet was received that was
not either a DHCPDISCOVER or DHCPREQUEST. Which we just don't need
to respond to, and no reason to log an error.
=> remove unnecessary error 'unable to create DHCP reply'

installers/vmware/kickstart-esxi.go
This adds the --firstdisk option to the VMware installer, specifically for the m3.large.x86 server plan.
=> Add vmware firstdisk for m3.large.x86

packet/models.go, packet/models_test.go
Removed the [`Storage`](https://github.com/tinkerbell/boots/blob/master/packet/models.go#L150) field under `Instance`
The `Storage` field was erroneously added in a [previous commit](https://github.com/tinkerbell/boots/pull/27), which made boots try to parse [`partition.size`](https://github.com/tinkerbell/boots/blob/master/files/ignition/storage.go#L32) (which can either be an int or string) and was crashing the code.
Fixes: #
I have:
=> removed Storage as a field under Instance

go.mod, installers/vmware/ipxe_script_test.go, ipxe/settings.go, job/dhcp.go, job/dhcp_test.go, job/events.go, job/events_test.go, job/fetch.go, job/hardware.go, job/helpers.go, job/job.go, job/job_test.go, job/mock.go, job/network.go, packet/client.go, packet/endpoints.go, packet/models.go, packet/models_cacher.go, packet/models_test.go, packet/models_tinkerbell.go, packet/util.go
Change from pointers to interface to just an interface for the recent data model split. Took the opportunity to clean up some of the related tests so they would be more correct (when setting env vars) / easier to follow (making TestNewDiscoveryMismatch not panic). 
I think #27 was merged prematurely. Lots of commented out code that should have been deleted, oddness in the pointer-to-interface and some hard to follow tests. This is me polishing some of that up.
Fixes: #
`go test ./...`
No anticipated impact.
I have:
=> Cleanup after new data model

installers/osie/main.go, installers/osie/mirror.go, job/dhcp.go, job/helpers.go, job/mock.go, packet/models.go, packet/models_cacher.go, packet/models_test.go, packet/models_tinkerbell.go
Bring in changes that were merged into the `production` branch, and thus deployed into Packet's actual production system, back into master. This was done while master was in a state that would break Packet provisioning.
With this merged we can get back to having Packet working off of `master` branch.
`go test` passes.
Tested in both YYZ1 and NRT1, provisions/deprovisions working well.
No anticipated issues.
I have:
=> Production into master

packet/endpoints.go, packet/models.go
Missed some sections that have logic dealing with DATA_MODEL_VERSION.
To be future compatible with any new DATA_MODEL_VERSION revisions.
Compiles.
No impacted expected.
=> Stricter data model version handling

go.mod, go.sum, packet/endpoints.go
The [metadata](https://github.com/tinkerbell/tink/blob/a2944c1dd079bd72b61cb955919524fc4542f14c/protos/hardware/hardware.proto#L221) field under hardware is being changed to a (json formatted) string in Tink.  
In order to accommodate that, this PR uses a custom unmarshaller for the `hardware.Hardware` object returned from tink to be able to parse the json formatted string.
Fixes: https://github.com/tinkerbell/tink/issues/199
- Successfully ran a basic workflow using a tinkerbell/packet setup
Should work as before, no migration needed.
Related PRs:
hegel: https://github.com/tinkerbell/hegel/pull/16
tink: https://github.com/tinkerbell/tink/pull/197
I have:
=> ENG-6658 user defined metadata

.github/CODEOWNERS
Add site-eng as CODEOWNERS
To avoid having PRs merged without site-eng taking a look with a packet-production perspective by having site-eng automatically set as a reviewer.
=> Add site-eng as CODEOWNERS

go.mod, go.sum, job/tftp.go, tftp.go
In some cases we hit an issue with mtu and tftp in cilium. This change
includes a fix to reduce the block size to 1400 which has been working
well under cilium.
=> use tinkerbell/tftp-go for fixed block size

conf/config.go, installers/osie/ipxe_script_test.go, installers/osie/main.go, ipxe/dhcp_options.go, job/ipxe.go
This allows for a separate host to be defined as the syslog server.
The default action is to fallback to the `PublicIPv4` which is what
is currently used as the DHCP Log Server option value.
You can now define both `PUBLIC_SYSLOG_IP` and `PUBLIC_SYSLOG_FQDN`.
The former is needed to change the dhcp log server. The latter is
passed into the ipxe script.
If the fqdn is not defined, it falls back to the value of the ip.
If the ip is not defined it falls back to the public ip.
=> include syslog host in osie kernel environments

installers/vmware/kickstart-esxi.go, installers/vmware/testdata/vmware_base.txt
This adds the interpreter definition to VMware installer for a few post install directives within the kickstart portion of the VMware installer.
This change addresses a hang during the ESXi installation and resolves 2 warning messages.
Testing is completed by deploying to a single facility prior to general production deployment.
Fixes a bug which was causing a ~30 second delay during legacy/kickstart based installation of VMware.
I have:
=> Add interpreter definition to VMware installer

go.mod, go.sum
The PR updates Boots to use the latest version of `packethost/pkg/log` package.
Required for dependent [PR tink #271](https://github.com/tinkerbell/tink/pull/271).
Tested by executing an end-to-end workflow.
=> Update packethost/pkg  version

installers/coreos/installer.go
For the s3.xlarge plan type, lets exclude NVMe disks from the installation targets
Seems Flatcar isn't working well with those. Also they are marked for cache instead of boot in any case.
Confirmed NVMe only installs seem broken by creating m3.large NVMe only setup.
Barely tested otherwise.
No break, only fix 🤞
=> flatcar: exclude NVMe disks for s3.xl

conf/mirror.go, conf/mirror_test.go, installers/vmware/ipxe_script_test.go, installers/vmware/kickstart_script_test.go
Signed-off-by: Jason DeTiberus <detiber@users.noreply.github.com>
We were generating a value for the MirrorBaseIP variable that caused issues when specifying a MIRROR_BASE_URL or MIRROR_HOST value that contained a port number, however MirrorBaseIP is never referenced anywhere other than a couple of tests where it is being overridden (to no effect).
This allows users to specify MIRROR_BASE_URL or MIRROR_HOST that contains a host:port combination, when the mirror server is not listening on port 80
Tested using the local setup described in the docs, slightly modified to expose the mirror host on a port other than port 80.
This should not affect existing users.
I have:
=> Remove unused MirrorBaseIP variable and associated functions

installers/coreos/ignition.go, installers/coreos/installer.go, installers/coreos/installer_test.go
Currently it seems that Flatcar encounters a race condition on some of 
our hardware. This fix was suggested by @t-lo and crafted by 
@nicolerenee
Adjust the systemd unit we use to wait for network connectivity
Recently Flatcar stopped working on c1 and c3 small.x86 plan types
Highly speculative, untested
No break, only fix 🤞
=> flatcar: move to systemd-network

installers/coreos/installer.go, installers/coreos/installer_test.go
Lets point at the service instead of the target. Credit to @nicolerenee
Fixes a small oversight in #88 where the target is now a service
=> flatcar: networkd switch from target to service

installers/osie/main.go
Seems these new HP machines use this TTY instead
For the f3.medium and f3.large plans, lets use ttyS0 instead
Not working on ttyS1
=> f3.x86: opt for ttyS0 instead

.github/workflows/ci.yaml, shell.nix
Hopefully this fixes golangci-lint action spamming CI with unrelated errors. This is both noisy in the stderr output and also ends up failing the action itself. For example:
https://github.com/tinkerbell/boots/runs/1344481754?check_suite_focus=true#step:6:64
> Error: /bin/tar: ../../../go/pkg/mod/github.com/andreyvit/diff@v0.0.0-20170406064948-c7f18ee00883/doc.go: Cannot open: File exists
=> Update golangci lint action

.github/workflows/ci.yaml
This PR adds linux/arm/v6,linux/arm/v7,linux/arm64 platform as target for Docker
Images.
=> Add arm platforms as part of docker image release

packet/models.go, packet/models_cacher.go, packet/models_tinkerbell.go
I missed this in the last PR that moved things around.
=> packet: Move the Discover* structs to respective models_* file

.github/workflows/ci.yaml, Dockerfile, Makefile, shell.nix
The docker images we built are multi-arch, but for some reason the boots binary inside is x86 for all of them.
We need the right binary with the right architecture 
Not tested yet but it will be locally.
The user is currently impacted because Docker images and binaries released as part of sandbox only works for x86.
=> Docker image does not contain the right binary

installers/osie/main.go
Includes the instance id in the kernel parameters passed into the osie installer.
This allows us to avoid querying for metadata simply to look up the current instance uuid.
=> Include instance_id in kernel cmdline parameters

go.mod, go.sum, job/dhcp.go, job/dhcp_test.go, job/events.go, job/events_test.go, job/helpers.go, job/ipxe.go, job/mock.go, packet/models.go, packet/models_cacher.go, packet/models_test.go, packet/models_tinkerbell.go
This PR fixes the mismatch in field names [`operating_system_version`](https://github.com/tinkerbell/tink/blob/master/protos/packet/packet.proto#L86) vs [`operating_system`](https://github.com/tinkerbell/hegel/blob/a3138d417536903dcdedd674d634e13ebc19fc79/http_handlers.go#L33).
v2 of https://github.com/tinkerbell/boots/pull/104
This bug mainly affects the users who needs both the `packet.pb.go` and the EC2 endpoint. Because the EC2 endpoint in Hegel uses the field name `operating_system` to be backwards compatible with Kant, users using the `Metadata` object defined in `packet.pb.go` will face a problem with parsing the operating system field since it was defined as `operating_system_version` there. 
The reason for the mismatch is because in the "old" cacher mode, …
=> add 'operating_system' field into Instance for tinkerbell mode

README.md
Change build status badge in README from Drone to GitHub Actions
We don't use Drone any more.
=> Replace Drone badge with GitHub Action badge

job/job.go, job/job_test.go
When checking for the status of a 'job' boots currently only considers PENDING workflows.   This change makes it consider RUNNING workflows to be 'active' as well.
During workflow execution we pass status updates back to our central API by way of boots.   As-is, the hasActiveWorkflow function will reject those status updates as it only considers 'PENDING' workflows to be active.
=> hasActiveWorkflow should consider workflows in state PENDING and RUNNING

ipxe/ipxe/common.h
Bring back the `set` ipxe command.
Was removed in #117 by mistake.
Boot tested.
=> ipxe: add "set" command to config

.gitattributes, .github/workflows/ci.yaml, ipxe/.gitignore, ipxe/bin/.gitignore, ipxe/bin/ipxe.efi, ipxe/bin/snp-nolacp.efi, ipxe/bin/undionly.kpxe, ipxe/bindata.go
Removes the iPXE binaries we can actually build out of GitLFS.
This makes it easier for contributors to contribute since we
don't have to reproduce or over write the ixpe builds they
contribute. This does mean the project isn't `go get`able but
I guess we'll just have to live with that.
Closes #116
N/A
=> ipxe: Do not vendor binaries in git lfs

http.go, installers/osie/main.go, job/events.go, job/helpers.go, job/job.go, packet/endpoints.go, packet/endpoints_test.go, packet/models.go, packet/models_cacher.go, packet/models_tinkerbell.go, tftp.go, tftp/tftp.go
Provided the correct ID to `job.HasActiveWorkflow` along with better error handling and logging.
We were passing the job.ID() to HasActiveWorkflow which is the machine's primary mac address, this
is not what the gRPC call actually wants. There was also an error where we'd send back success/0 content
instead of an error if there's a problem fetching workflows or if there is no workflow active.
This PR changes the HardwareID from a string to a type so that we can avoid using and passing the wrong strings around.
Unit tests, and running it.
Bug is fixed.
=> Fix use of HasActiveWorkflow

installers/nixos/ipxe_script_test.go, installers/nixos/main.go, job/mock.go
Use EM OSV imagetag as a possible store of the NixOS store path values.
Better support for @grahamc and NixOS for EM provisions.
Unit tests so far.
I have:
=> NixOS: Look for config from OSV imagetag if not in env

http.go, job/job.go, tftp.go
Currently, a machine will only PXE boot if it has an existing tink workflow.
To do any other type of PXE boot (custom ipxe, osie, hook, etc) you have to create a workflow that will never actually be run.
This commit allows machines to PXE into OSIE, hook, OSIE alternative, custom ipxe, etc without needing a workflow.
PXE booting will be gated by the tink hardware data field: `network.interfaces[].netboot.allow_pxe`
Allows machines to PXE boot without a workflow.
Fixes: https://github.com/tinkerbell/boots/issues/114
I built the boots image and ran it with the vagrant sandbox locally to test. It worked as intended there. 
no migrations.
I have:
=> Allow PXE booting regardless of an existing workflow:

.github/workflows/ci.yaml, Makefile, dhcp_test.go, go.mod, go.sum, tftp.go, tftp_test.go
tftp ReadFile was missing a return if AllowPxe was false.
This adds the return and adds tests for the AllowPxe
gate that was just recently added.
this library: https://github.com/bouk/monkey, was used in the unit tests and requires running tests with `-gcflags=-l`.
the github actions were updated to accommodate this.
a few testing helpers were added to the makefile.
Fixes: #
I have:
=> Fix tftp ReadFile, Add tests:

job/dhcp.go, job/dhcp_test.go, job/job.go, main.go, packet/models.go, packet/models_cacher.go, packet/models_test.go, packet/models_tinkerbell.go
Boots should check the provisioiner_engine metadata value against the PROVISIONER_ENGINE_NAME runtime environment to decide if it should be handling DHCP requests for a given piece of hardware.
To allow for multiple differing versions of boots to be running in an environment, with DHCP relayed to both simultaneously to aid in blue/green deployment testing.
=> support the provisioner_engine metadata value

Makefile
Change the `go generate` calls from blindly being run to instead be run as proper
make deps and targets.
The previous setup was unnecessarily calling `go generate` multiple times but only for the "cross compiled" binaries and not for the default target. Also, this wasn't actually regenerating
the syslog files because it wasn't diving into subfolders.
So now we fix both issues by recursing into all subfolders and also adding proper make deps/targets. 
Manually
=> Fix go generate call from Makefile

http.go
Only checks for workflows if we're in tinkerbell mode and setup for workflows.
Would break EM provisions for legacy sites.
Locally via docker-compose.
EM users get a fancy new boots release.
=> http: Only check for HasActiveWorkflow if CanWorkflow is true

installers/custom_ipxe/ipxe_script_test.go, installers/nixos/ipxe_script_test.go, installers/osie/ipxe_script_test.go, installers/rancher/ipxe_script_test.go, installers/vmware/ipxe_script_test.go, installers/vmware/kickstart_script_test.go, job/dhcp_test.go, job/events_test.go, packet/endpoints_test.go, packet/util_test.go
Use `t.Run` in all the table driven tests.
Using `t.Run` gives us better selectivity with `go test -run` and also better grouping/splitting when running with `go test -v`.
Just minor test changes, so tested with `go test`.
=> Refactor all table driven tests to use t.Run

README.md
Add helper description to README to assure people that running boots on their local networks is OK
closes #10
I was curious if this would be a problem and happened to find Alex's issue about the same thing.
I have:
=> docs: answer 'is it safe?' question for local networks

installers/vmware/kickstart-esxi.go, job/helpers.go, job/helpers_test.go, job/mock.go, packet/models.go
Have the vmware boots installer use a new `PasswordHash` field for its root password.
Fixes: #
I have:
=> Update vmware installer:

ipxe/.gitignore, ipxe/bin/.gitignore, ipxe/ipxe/common.h
Explicitly enable HTTP sanboot per #157
It seems that the binaries stored in git-lfs likely were built with sanboot enabled and apparently some people seem to have been depending on that functionality.
Fixes: #157
I manually booted qemu, had it chainload to `undionly.kpxe`, and verified that I could drop to the ipxe shell and run
```
dhcp
sanboot http://boot.ipxe.org/freedos/fdfullcd.iso
``` 
Fixes #157
I have:
=> Re-enable HTTP sanboot

installers/nixos/main.go, installers/osie/main.go, installers/vmware/kickstart-esxi.go, job/helpers.go, job/helpers_test.go, packet/models.go
Combines the 2 separate password getters (CryptedRootPassword and GetPasswordHash) into just one (PasswordHash).
Deploying without this breaks the legacy production system for ESXi deployments. The vmware
installer was changed to grab the password from where we'd expect it in tinkerbell mode only.
Unit tests.
=> Fix password look up to look in both possible locations

installers/vmware/main.go
Enable a VCF specific install path in a future merge
Expanding new network modes via VMWare ESXi
Fixes: #
Untested. Need API support to test.
Un-used code path until enabled by an API
I have:
=> Add support for VMWare VCF on ESXi 6.x and 7.x

README.md, shell.nix
This change allows `nix-shell` to work on Linux and macOS, without changes.
Currently, the `README.md` suggests macOS users should modify the `shell.nix` file to get it to work.
I have:
=> fix: ensure nix-shell works with Darwin

Makefile, docs/DESIGN.md, rules.mk, shell.nix
Currently building IPXE on a Mac is difficult and almost entirely manual, if not impossible even with the nix shell.nix.
This will leverage docker to make building IPXE on Mac just as easy as on Linux with the `make bindata` target call.
Building iPXE on Mac seems to not be a straightforward process.
Fixes: #
I have:
=> Build IPXE on darwin easier:

installers/vmware/kickstart-esxi.go, installers/vmware/testdata/vmware_base.txt
Adding a sleep to allow network devices to settle
We see a lot of install failures that look to be network interface not settling fast enough
Custom iPXE test deploy
30 sec longer install time
I have:
=> vmware: Add a pause in pre-install to quell network devices

.github/workflows/ci.yaml
Run ci builds on our self hosted, bare metal runners.
Faster builds/results especially for the iPXE builds.
GitHub Actions
Faster test cycles
I have:
=> ci: Run builds on our self hosted builders

.github/workflows/ci.yaml
Fix the docker-buildx ci workflow. This is a revert of one of the changes in #148.
#165 fails to build without this change
#159's build is also failing, likely for the same reason. 
Also #126 is probably blocked for the same reason...
Applied this commit to #165 and the builds then succeeded.
=> Add Docker Buildx back into the ci workflow

.github/workflows/ci.yaml, Makefile, ipxe/ipxe/build.sh, ipxe/test/sanboot.expect, ipxe/test/sanboot.pxe, rules.mk, shell.nix
While this doesn't directly exercise the ipxe binaries we bake into boots,
it does use the ipxe configs to build an `ipxe.lkrn` binary to use for testing features.
This test uses expect and qemu to exercise the sanboot feature.
Related to #157
`make test-sanboot` succeeds.
Additionally, cherry-picking this commit onto 5d563d8 fails as expected.
N/A
I have:
=> Automated test of ipxe config to confirm sanboot functionality

.github/workflows/ci.yaml, .gitignore, Makefile, go.mod, ipxe/ipxe.go, ipxe/ipxe/build.sh, rules.mk, shell.nix, tftp/tftp.go, tools.go
This PR removes the dependency on `go-bindata` and uses the builtin `embed` package of Go >1.16.
Go is being pinned in the nix-shell because moving all the dependencies to the same rev as the Go dependency caused ipxe builds to fail.
```bash
drivers/bus/isa.c: In function 'isabus_probe':
drivers/bus/isa.c:52:4: error: array subscript [-1073741824, 1073741823] is outside array bounds of 'isa_probe_addr_t[0]' {aka 'short unsigned int[0]'} [-Werror=array-bounds]
52 |    *( isa_extra_probe_addrs + (ioidx) + ISA_EXTRA_PROBE_ADDR_COUNT ) )
|    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/bus/isa.c:113:18: note: in expansion of macro 'ISA_IOADDR'
113 |    isa->ioaddr = ISA_IOADDR ( driver, ioidx );
|                  ^~~~~~~~~~
drivers/bus/isa.c:34:25: note: while …
```
=> Use builtin go embed

installers/vmware/kickstart-esxi.go, installers/vmware/kickstart_script_test.go, job/helpers.go, job/mock.go, packet/models.go
When installing VMware, it can be helpful to provide a detailed hint as to which disk the VMware installer should use.
This commit adds support for `instance.boot_drive_hint` in the hardware metadata which will be read when generating the VMware kickstart file.
On some of our hardware types (our storage nodes in particular) the VMware installer will sometimes choose the wrong disk. Providing a better hint to the installer should prevent those issues.
Fixes: Internal ticket: PROV-16
This currently only affects hardware whose plan slug starts with "s" which corresponds to EM storage hardware nodes.
To change that to affect all plans
```shell
git grep -l -E '& strings.HasPrefix(.*, "s")' | xargs sed -e 's|&& strings.HasPrefix(.*, "s") ||' -i
```
and verify that tests still pass and clean up …
=> EM specific: VMware installer should respect boot_drive_hint for --firstdisk

conf/config.go, installers/osie/main.go
In order for OSIE to write data to Hollow, we need to use these secrets
to request a temporary auth token.
We recognize that Equinix Metal specific code needs to be extracted from
Boots, and are looking into general solutions that will allow users to
specify secrets or custom kernel boot parameters.
=> Add OSIE secrets required by Hollow

Dockerfile, README.md, docker-compose.yml, test/Dockerfile, test/start-boots.sh, test/test-boots.sh
Adds a docker-compose.yml with a custom network config that simulates an L2 network well enough that we can validate DHCP requests.
This PR is just the basics of what we can do. It runs boots in standalone mode and dhcpcd in debug mode so a developer can visually confirm their code hasn't broken things.
Down the road we can use something like Bats and write automated tests for DHCP, tftp, and HTTP using standard clients.
With this in place I need to move onto the otel work, but will probably come up with some follow-on PRs to add tests as I lace otel into boots.
It makes smoke testing and local iteration more accessible.
```sh
docker-compose down
docker-compose build --no-cache
docker-compose up
```
The output currently looks like this:
```
tobert@linux ~/src/boots $ docker-compose up …
```
=> add docker compose configuration and test container

docs/IPXE.md, ipxe/ipxe/common.h, ipxe/test/ping.expect, ipxe/test/ping.pxe, rules.mk
Enable the built in ping command inside of the iPXE environment.
Operators debugging network issues sometimes find it useful to be able to issue ping commands from the iPXE environment to verify network configuration.
The added test exercises the change.
No impact
I have:
=> Enable the iPXE ping command

Dockerfile
Change the Docker container to build from Alpine 3.13 rather than 3.14 to address the build failures.
The build is currently broken for arm.
Fixes #186 
The test is the build pipeline.
=> Back down to Alpine 3.13

cmd/boots/http.go
This duplicate was missed during a rebase of the main branch.
Boots panics at runtime
Fixes: #
I have:
=> Fix panic: http: multiple registrations for /hardware-components:

cmd/boots/main.go, job/job.go, packet/client.go, packet/endpoints.go, packet/endpoints_test.go
Signed-off-by: Micah Hausler <mhausler@amazon.com>
Refactor `packet.Client` to an interface
This codifies the calls boots makes to backends. This is prep work for tinkerbell/proposals#46
Fixes: 
N/A
```
$ make test
CGO_ENABLED=1 go test -race -coverprofile=coverage.txt -covermode=atomic  ./...
ok  	github.com/tinkerbell/boots/cmd/boots	0.107s	coverage: 12.0% of statements
ok  	github.com/tinkerbell/boots/conf	0.034s	coverage: 50.0% of statements
?   	github.com/tinkerbell/boots/dhcp	[no test files]
?   	github.com/tinkerbell/boots/files/ignition	[no test files]
?   	github.com/tinkerbell/boots/files/tarball	[no test files]
?   	github.com/tinkerbell/boots/files/unit	[no test files]
?   	github.com/tinkerbell/boots/httplog	[no test files]
?   	github.com/tinkerbell/boots/installers	[no …
```
=> Abstract Packet client

installers/osie/main.go
Found a method to ensure those plans were on ttyS1 and so we won't need 
to adjust to ttyS0 anymore.
Signed-off-by: Dustin Miller <dustin@packet.com>
Remove plan specific actions for console tty settings
More defaults and less Metal specific things is good
Just in theory
No break, only fix :crossed_fingers:
=> installers: remove f3 plan specific tty

README.md
We're linking to the GH repos directly in various marketing content, so we need to direct users back to the main site.
Fixes: #
I have:
=> Added link back to website

cmd/boots/main.go, packet/client.go, packet/endpoints.go, packet/endpoints_test.go
Discovery requests call an external service, by logging this, it's
easier to track a request when it takes this path.
=> log discovery requests

installers/vmware/kickstart-esxi.go, installers/vmware/kickstart_script_test.go
Signed-off-by: Dustin Miller <dustin@packet.com>
Lets use the the BootDriveHint method for plans which start with `w` as well
Picking the wrong disk has negative impacts on provisioning
Just theory
No break, only fix :crossed_fingers:
=> installers: apply bootdrive hint for w plans

installers/vmware/kickstart-esxi.go, installers/vmware/testdata/vmware_base.txt
The VMware installer was previously relying on wget's "-s" or spider option to determine whether or not a particular URL was accessible while handling the customdata portion of the kickstart. This option is not valid on the version of wget which ships with current closed-source ESXi installers.
This change fixes a bug related to the customdata logic responsible for executing the kickstart postinstall scripts and kickstart firstboot install scripts provided via customdata.
Fixes: #
CI testing
Fixes customdata bug and unblocks further VMware VCF configuration.
I have:
=> kickstart esxi: Remove the -s option from wget

.gitignore, cmd/boots/tftp.go, dhcp/pxe.go, ipxe/dhcp_options.go, ipxe/files.go, job/dhcp.go, job/dhcp_test.go, job/http.go, job/job.go, job/logging.go, rules.mk, tftp/tftp.go
This adds supports for UEFI HTTP Boot.
Fixes: #210 
Tested with:
* [QEMU OVMF (AMD64)](https://github.com/tianocore/tianocore.github.io/wiki/OVMF) (HTTP and TFTP Boot)
* [RPi4-UEFI (ARM64)](https://github.com/pftf/RPi4) (HTTP and TFTP Boot)
* [RPi4-UEFI-iPXE (ARM64)](https://github.com/rgl/rpi4-uefi-ipxe) (HTTP and TFTP Boot)
* [Seeed Studio Odyssey X86J4105 board (AMD64)](https://wiki.seeedstudio.com/ODYSSEY-X86J4105/) (HTTP Boot)
* [HP EliteDesk 800 35W G2 Desktop Mini (AMD64)](https://support.hp.com/us-en/product/hp-elitedesk-800-35w-g2-desktop-mini-pc/7633266) (TFTP Boot)
Should have no impact.
I have:
=> add support for UEFI HTTP Boot

installers/osie/ipxe_script_test.go, installers/osie/main.go
Enable c3.large.arm IOMMU
Enable PCI Pass-through and IOMMU as defaults
Signed-off-by: My D. Truong <truongmd@gmail.com>
Enables PCI pass-through and IOMMU across the board
Fixes: #
Hand test on running systems
No expected impact
I have:
=> Enable PCI pass-through and IOMMU as defaults

.gitignore, cmd/boots/tftp.go, dhcp/pxe.go, ipxe/dhcp_options.go, ipxe/files.go, job/dhcp.go, job/dhcp_test.go, job/http.go, job/job.go, job/logging.go, rules.mk, tftp/tftp.go
This reverts commit ceb470a66c889147c78106ecaece0fafa26b88af.
Something in #216 broke our c2.large.arm provisions. Reverting
this to unblock things that came after while I look into debugging.
Some more info in [#225].
[#225]: https://github.com/tinkerbell/boots/issues/225
Tested via sandbox against EM c2.large.arm
=> Revert "add support for UEFI HTTP Boot"

installers/osie/main.go
The BIOS on these servers restrict console support to COM0.
=> osie installer: use ttyS0 as console for w3amd.75xx24c.256.4320.x86

cmd/boots/dhcp.go, cmd/boots/main.go, job/dhcp.go, job/dhcp_test.go, job/job.go
With the splitting out of ipxedust, the goal is for boots to be able to send DHCP responses
that point to a separate ipxedust server. The code didn't fully make that distinction
all the way down to the DHCP responses.
Reverts #246 
Fixes the issue identified in #246
I have:
=> Disambiguate ipxe HTTP URLs from other boots URLs

cmd/boots/main.go, installers/osie/ipxe_script_test.go, installers/osie/main.go, job/helpers.go
An override for `alpine` was defined that forced any alpine distro to trigger the rescue environment.
This isn't great logic as Alpine is a true OS and may want to be provisioned.
This changes the default installer to detect whether Rescue was requested and trigger the rescue path when enabled.
To cleanup old logic that doesn't make sense and allow for an Alpine OS to properly boot to the default installer.
Fixes: #
I have:
=> switch to handling rescue with the default installer

installers/osie/main.go, installers/osie/mirror.go
Allow registry, registry username, and password to be empty strings. These values are passed as kernel command line args for OSIE's boot up and then used by Tink worker when it pulls and runs containers. With [this](https://github.com/tinkerbell/tink/pull/607) change to Tink worker, allowing the empty string here provides Tink worker the ability to specify any fully qualified container image in a template. e.g. `docker.io/alpine`, `quay.io/tinkerbell-actions/cexec`, `public.ecr.aws/l0g8r8j6/tinkerbell/pbnj`, etc
This change is backward compatible and shouldn't negatively affect using the Cacher backend.
Fixes: #
I have:
=> Allow registry, registry username and password to be empty strings

cmd/boots/http.go, job/job.go
Set jobManager for HTTP server:
This fixes nil pointer dereference panic in func `serveJobFile` calling `jobHandler.jobManager.CreateFromRemoteAddr`. This panic was manifest when doing an HTTP Get for auto.ipxe
Also experiencing a nil pointer panic when calling `Job.Logger` in the job package.
Fixes: #
```bash
export API_AUTH_TOKEN=none
export API_CONSUMER_TOKEN=none
export DATA_MODEL_VERSION=standalone
export BOOTS_STANDALONE_JSON=./test/standalone-hardware.json
sudo -E go run ./cmd/boots/
curl -v http://<boots ip>/auto.ipxe 
```
```bash
2022/05/02 16:41:21 http: panic serving 192.168.0.240:59216: runtime error: invalid memory address or nil pointer dereference
goroutine 114 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1825 +0xbf
panic({0x1795a00, …
```
=> Fix server panics

cmd/boots/main.go, cmd/boots/main_test.go, installers/osie/main.go
This allows operators to set any necessary and needed kernel commandline args to the default installer; OSIE. This makes custom kernel args a first class option instead of the current model to overload the "facility" field in the backend data.
Fixes: #
I have:
=> Allow extra kernel args, set via cli flag:

client/cacher/hardware_finder.go, client/cacher/hardware_finder_test.go, client/noop_reporter.go, client/packet/endpoints.go, client/reporter.go, cmd/boots/main.go
An EM specific regression popped up due to #255 where `GetDiscoveryFromEM` isn't being called anymore (color me surprised thats all we noticed :smile:). This fixes it and adds some tests for the fallback behavior.
Reinstates the cacher mode behavior of falling back to trying to fetch some data from EMAPI.
Unit tests. Ran against cacher/emapi using sandbox.
No more missing fallback for EM.
=> Fix regression from data-model refactor

cmd/boots/main.go, cmd/boots/main_test.go, installers/osie/ipxe_script_test.go, installers/osie/main.go
Add CLI flag for overriding OSIE path
If an OSIE download path URL is specified via this fkag, OSIE_PATH and
MIRROR_HOST variables that are used to build OSIE URL will be ignored.
Hardcoded appending of 'misc/osie' and 'current' directories to the path
will be bypassed.
With the ongoing refactoring efforts, once all this hardcoded appending 
of paths is cleaned up, this flag can be removed/modified.
Signed-off-by: Pooja Trivedi <tripooja@amazon.com>
Fixes: #
I have:
=> CLI flag to allow overriding of OSIE path

installers/flatcar/installer.go, installers/flatcar/installer_test.go, installers/flatcar/ipxe_script_test.go, installers/flatcar/main.go
This is part of an ongoing effort to consolidate the sources of OS images, and uses a base url from the Boots environment to be a bit less hard-coded.
=> flatcar installer: Use vendor services url to download OS images

client/instance.go, installers/vmware/kickstart.go, installers/vmware/kickstart_test.go, installers/vmware/testdata/ks_.txt, installers/vmware/testdata/ks_KXG50ZNV256G_TOSHIBA,vmw_ahci.txt, installers/vmware/testdata/ks_hint.txt, installers/vmware/testdata/ks_lsi_mr3,lsi_msgpt3,vmw_ahci.txt, installers/vmware/testdata/ks_lsi_mr3,vmw_ahci.txt, installers/vmware/testdata/ks_vmw_ahci,lsi_mr3,lsi_msgpt3.txt, installers/vmware/testdata/ks_vmw_ahci.txt, installers/vmware/testdata/vmware_base.txt, job/helpers.go, job/mock.go
The password on an instance is typically a generated password.
For VMWare an alternative password hash can be provided via the
instance's customdata field.
Previously the method for utilizing that override required manipulating the shadow file.
This method is no longer supported by vmware, as the shadow file is generated based off a database value.
The correct way to set the root password is through the kickstart file.
We already were setting the generated password, so we could simply add
the necessary logic to check for an overwritten password instead.
The previous hack of editing /etc/shadow no longer works as that file is overwritten at startup.
Fixes: #
I have:
=> support esxi 7.0.1+ root password hash changes

installers/osie/ipxe_script_test.go, installers/osie/main.go, job/dhcp.go, job/dhcp_test.go, job/helpers.go
Drops all use of parch.
Gets rid of an EMism and makes it so we only ever boot one kernel per cpu arch.
Unit tests and ran in EM. Non-EM was never affected.
=> Drop EMism - PArch

installers/vmware/kickstart.go, installers/vmware/kickstart_test.go, installers/vmware/testdata/ks_KXG50ZNV256G_TOSHIBA,vmw_ahci.txt, installers/vmware/testdata/ks_hint.txt, installers/vmware/testdata/ks_lsi_mr3,lsi_msgpt3,vmw_ahci.txt, installers/vmware/testdata/ks_lsi_mr3,vmw_ahci.txt, installers/vmware/testdata/ks_vmw_ahci,lsi_mr3,lsi_msgpt3.txt, installers/vmware/testdata/ks_vmw_ahci.txt
A first disk hint may have a space which would break the option.
Additionally, vmware truncates the model version to 16 characters.
The drive reported model may contain a space which if provided as a hint would break this command.
If the model in the hint is longer than 16 characters we need to truncate to match vmware expectation.
Fixes: #
I have:
=> fix vmware firstboot disk

installers/vmware/kickstart.go, installers/vmware/testdata/ks_.txt, installers/vmware/testdata/ks_KXG50ZNV256G_TOSHIBA,vmw_ahci.txt, installers/vmware/testdata/ks_hint.txt, installers/vmware/testdata/ks_lsi_mr3,lsi_msgpt3,vmw_ahci.txt, installers/vmware/testdata/ks_lsi_mr3,vmw_ahci.txt, installers/vmware/testdata/ks_vmw_ahci,lsi_mr3,lsi_msgpt3.txt, installers/vmware/testdata/ks_vmw_ahci.txt, installers/vmware/testdata/vmware_base.txt
This PR removes the additional iSCSI and IQN config that was previously required to support a specific third-party storage provider which has since been decommissioned.
The base level iSCSI config interferes with VMware ESXi users who are using their own iSCSI storage solutions.
Fixes: #
Testing via CI
Fixes a customer issue relating to iSCSI storage.
Requires a customer notification before deployment.
I have:
- [X ] updated the documentation and/or roadmap (if required)
- [X ] added unit or e2e tests
=> Remove iSCSI and IQN config

installers/osie/ipxe_script_test.go, installers/osie/main.go
Ensure that packet_base_url will always be added to the kernel args.
Avoid needing to have defaults in OSIE or other boot systems. This will allow us to remove some EMisms in the near future.
Unit tests.
=> ensure kernel args always has packet_base_url populated

.github/workflows/ci.yaml, .github/workflows/tags.yaml
Split container build and push to different steps to avoid confusion.
We recently tried deploy a tag that was never pushed to quay because we didn't notice it was for a PR and not for a build off of main. It seems like a good idea to avoid having to go digging into the build's output and try to figure out if it was actually pushed or not.
CI.
=> Split docker build and push into different steps

client/kubernetes/cluster.go, client/kubernetes/hardware_finder.go
Currently, the kube client for boots needs a cluster role permission to fetch Hardware and Workflow CRs, even if the resources and the client are namespaced. This will lead to extending boots rbac to cluster role instead of using namespaced roles. It seems that, the current client creation doesn't scope the client to a namespace(the rest config type that is returned doesn't have a context, thus there will be no Namespace scoped anywhere in the client).     
Enabling kube client operation on Namespaced scoped resources
Fixes: #
Ran against a live cluster and the indexer succeeded to list the needed resources. 
They are not as they can pass whatever rbacs they like, based on their setup. 
I have:
=> Add a namespace for the cluster client

go.mod, go.sum
This resolves a regression in the previous version that could cause come hardware to panic or fail to DHCP properly when loading the iPXE binary.
Fixes: #
I have:
=> Update ipxedust version:

conf/config.go, installers/osie/ipxe_script_test.go, installers/osie/main.go
With the recent addition of the CLI flag `-extra-kernel-args` all of the packet (equinix metal) specific kernel args in the auto.ipxe of the OSIE installer can now be specified at runtime instead of compiled in.
Fixes: #
I have manually tested this with the sandbox repo.
I have:
=> Remove references to packet in auto.ipxe for OSIE installer:

installers/osie/ipxe_script_test.go, installers/osie/main.go
When tagged VLANs are enabled `ip=dhcp` in the kernel will always fail as the vlan interface hasn't been created yet. It also has to timeout before moving on and add significant delay to Hook's boot up time. The kernel arg `hw_addr` has been added to help in creation of the tagged interface.
Fixes: #
I have:
=> Don't add kernel arg `ip=dhcp` for tagged vlans:

cmd/boots/main.go, cmd/boots/main_test.go, go.mod, go.sum
Update ipxedust and exposes the binary patching functionality added in https://github.com/tinkerbell/ipxedust/pull/63
New feature
N/A
I have:
=> Expose ipxedust script patching feature

syslog/message.go, syslog/receiver.go
The current syslog buffer size of 1024 was not enough to capture log messages from tink-worker. Also fixed the output of logs to not overwrite the structure key "msg".
Fixes: #
I have:
=> Increase syslog buffer size, fix key/value mapping:

ipxe/script/auto_test.go, ipxe/script/hook.go
When a machine had multiple interfaces that weren't all plugged in, this would cause significant delay in booting into Hook.
If necessary, this value can be added back in via the `-extra-kernel-args` cli flag.
Fixes: #
I have:
=> Remove kernel parameter ip=dhcp in auto.ipxe:

cmd/boots/env.go, cmd/boots/main.go, go.mod, ipxe/http/http.go, ipxe/http/middleware.go, ipxe/script/ipxe.go, syslog/receiver.go
This library has been archived. All the functionality exist in the stdlib now.
Fixes: #
I have:
=> Remove github.com/pkg/errors as a direct dependency:

ipxe/http/middleware.go
Func now only returns an error when the error is not nil.
logs were showing an error when there wasnt one.
```json
{"level":"error","ts":1695434959.912211,"caller":"script/ipxe.go:152","msg":"unable to write boot script","script":"auto.ipxe","error":"writing response: %!w(<nil>)","stacktrace":"github.com/tinkerbell/smee/ipxe/script.(*Handler).serveBootScript\n\t/home/tink/repos/tinkerbell/boots/ipxe/script/ipxe.go:152\ngithub.com/tinkerbell/smee/ipxe/script.(*Handler).HandlerFunc.func1\n\t/home/tink/repos/tinkerbell/boots/ipxe/script/ipxe.go:108\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2122\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.WithRouteTag.func1\n\t/root/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.42.0 …
```
=> Fix middleware writer:

README.md, cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, docker-compose.yml, go.mod, go.sum, ipxe/http/http.go, ipxe/http/middleware.go, ipxe/script/ipxe.go, ipxe/script/ipxe_test.go
This moves from using IP auth via the source IP address and the trusted proxies cli flag/env var to using the MAC address in the URL in order to determine the Hardware to lookup when serving the auto.ipxe. For example: `http://192.168.2.3/40:15:ff:89:cc:0e/auto.ipxe`
This opens up the `auto.ipxe` script to be able to be served across network address translation (NAT) layers and simplifies the deployment by not having to deal with the X-Forwarded-For (XFF) header.
Fixes: #
I have:
=> Remove trusted proxies around auto.ipxe:

README.md, cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go
Allows customizing TFTP blocksize at runtime.
Fixes: #368 
I have:
=> Add TFTP blocksize flag:

cmd/smee/backend.go, cmd/smee/backend_test.go, cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, go.mod, go.sum, shell.nix
They will eliminate issues from users having to determine the trusted proxies. We've seen issues where the command we provided in the Helm chart doesn't accurately get the pod CIDRs from a cluster. Incorporating this into the Helm chart was tried, but ultimately not possible without extra ordinary effort and a lot of unneeded code to maintain. This functionality can be disabled if desired. By default we run auto discovery.
This will help simplify the deployment of Smee in the Helm Chart.
Also, move go.mod to Go 1.21. This is because when developing with Go 1.21 and `go mod tidy` will update the `go.mod` file.
Dependency updates for tinkerbell/dhcp provide a fix for dhcp relays and the `giaddr`.
Fixes: #382 
I have:
=> Add auto discovery of trusted proxies in Kubernetes, relays and giaddr fix:

.github/workflows/ci.yaml, go.mod
This causes ci and dependabot issues. Also needed to use the `shell.nix` file in the CI "Fetch Deps" or newer versions of Go get used and cause changes to the go.mod.
Fixes: #
I have:
=> Remove toolchain from go.mod

CONTRIBUTING.md
Updating old documentation links to point to new locations. docs.tinkerbell.org -> tinkerbell.org/docs/
Old documentation is confusing for new users.
=> Updating old documentation links to point to new locations

cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, internal/ipxe/script/auto_test.go, internal/ipxe/script/hook.go, internal/ipxe/script/ipxe.go, internal/ipxe/script/ipxe_test.go
This will help overcome transient network issues.
Fixes: #333
I have:
=> Add retries to auto.ipxe kernel/initrd downloads:

README.md, cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, internal/ipxe/script/auto_test.go, internal/ipxe/script/hook.go, internal/ipxe/script/ipxe.go, internal/ipxe/script/ipxe_test.go
The iPXE kernel and initrd retries didnt work. This fixes them and adds a configurable retry delay.
Fixes: #
Tested via manual deployment and network booted a machine.
I have:
=> Ipxe hot fix

internal/dhcp/dhcp.go, internal/dhcp/dhcp_test.go
There are new mac prefixes for Raspberry PIs. Use mac address to determine Architecture for Raspberry PI's. This is needed because in my testing Raspberry PI 5 identifies itself in DHCP option 93 as an INTEL_X86PC.
Fixes: #
I have:
=> Update Raspberry PI mac prefixes:

cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go
This allows detectPublicIPv4 to be used and still allow the ports to be customized. This will be helpful in a few scenarios, one is when Smee is deployed with `hostNetwork: true` in Kubernetes.
Fixes: #475 
I have:
=> Break out port from most CLI flags:

cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go
This allows customizing the syslog port without having to customize the auto-detected ip. This is inline with the other similar changes just made.
Fixes: #
I have:
=> Split out syslog port

internal/dhcp/handler/proxy/proxy.go
When in proxyDHCP mode if AllowNetboot is false Smee would panic because of this log line. This resolves the issue.
Fixes: #482
I have:
=> Fix nil pointer error:

internal/dhcp/handler/proxy/proxy.go
Neither the error nor the netbootAllowed key/value pairs actually make it to the log line without this change.
Fixes: #
I have:
=> Fix missing assignment:

cmd/smee/backend.go, internal/backend/kube/kube.go
Single namespace look ups weren't functioning properly. They function properly now.
Fixes: #
I have:
=> Update kubernetes client creation for single namespace:

go.mod, go.sum
=> Update tink dependency

.golangci.yml, README.md, cmd/smee/flag.go
This allows just specifying an interface and letting the first IP on that interface be used for all CLI flag defaults.
Fixes: #
I have:
=> Set the default CLI IP for use based on a give interface name:

cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, internal/backend/kube/error.go, internal/iso/iso.go, internal/iso/iso_test.go
This change adds the ability in Smee to serve Hook as an ISO file through HTTP and also patch it with all the necessary dynamic information needed to connect with a Tink Server. 
Hook recently added an [feature](https://github.com/tinkerbell/hook/pull/241) to support building it as an ISO file. This change leverages that feature to be able to serve and patch Hook as an ISO file. This will be needed to be able to get Tinkerbell stack running on L3 without any Layer 2 dependency.  
Built a custom smee image with above changes, and tested with that image and replacing the smee deployment of Tink stack on a k3d cluster with real hardware. Set the Hardware to boot from Virtual media mount and verified that the hardware was able to boot properly.
ISO serving will not be enabled by default in …
=> Serve and patch Hook as an ISO during runtime

cmd/smee/main.go, go.mod
slog is one less import and by default provides improved time format and file, function, and line number attributes.
Fixes: #
I have:
=> Move to slog logr implementation:

internal/iso/iso.go
The DHCP handler interface has a method we don't need and didn't need to be a dependency of this package. Also, did some code reorganization and added some code comments.
Fixes: #
I have:
=> Remove dependency on DHCP handler interface:

README.md, cmd/smee/flag.go, cmd/smee/flag_test.go, cmd/smee/main.go, internal/iso/iso.go, internal/iso/iso_test.go
This adds optional static IPAM data to kernel parameters when patching an ISO.
Fixes: #
I have:
=> Add static ipam to kernel parameters for ISO patching:

README.md
=> Update readme cli flags example

.golangci.yml, internal/iso/internal/LICENSE, internal/iso/internal/acsii.go, internal/iso/internal/acsii_test.go, internal/iso/internal/context.go, internal/iso/internal/reverseproxy.go, internal/iso/internal/reverseproxy_test.go, internal/iso/ipam.go, internal/iso/ipam_test.go, internal/iso/iso.go, internal/iso/iso_test.go
The previous implementation only worked for clients that did partial content requests. This refactor allows all requests, whether partial content or not to have patching occur.
This is particularly useful when using the redfish emulator from sushy-tools. This emulator doesn't not request the ISO as partial content but requests the whole ISO like a curl or wget client might. This implementation is very memory safe and doesn't require content length checking of any kind. The Go stdlib httputil.NewSingleHostReverseProxy file and supporting files were copied in. This is because reimplementing all the logic in func (p *ReverseProxy) ServeHTTP of the httputil package is a lot and made more sense to copy it in and modify it to be able to patch when writing the body to the client.
Fixes: #
I …
=> Refactor ISO patching implementation:

go.mod, go.sum, internal/ipxe/http/http.go, internal/ipxe/http/xff.go, internal/ipxe/http/xff_test.go, internal/otel/otel.go
This repo is not maintained. Also, add license header for code copied from the no longer maintainer github.com/equinix-labs/otel-init-go repo.
Fixes: #
I have:
=> Remove github.com/packethost/xff dependency

internal/iso/iso.go
The default implementation of ReverseProxy provided by `NewSingleHostReverseProxy` does not rewrite the host header of the outbound request. Instantiate ReverseProxy with an implementation that rewrites the host header of the outbound request by default.
When the host header is not being rewritten, it would still have the host value that the incoming request had which in this case would be the smee host IP itself. If the upstream URL is hosted on a public service such as S3 which does some validations on the request header, the current implementation would fail as S3 would deny any such request where it's not able to validate the host header.
Fixes: #
Tested this change with isoURL in the smee deployment set to an S3 link and was able to boot up a Hardware properly.
I have:
=> Rewrite Host Header by default in ReverseProxy

internal/ipxe/script/ipxe.go
The object that gets returned from Kubernetes seems to always come back non-nil. So we need to also check if the string is empty.
Fixes: #
I have:
=> Fix how we check for OSIE.BaseURL:

internal/ipxe/script/auto.go
This PR changes the template package import from html/template to text/template in the iPXE script generation code (auto.go). The motivation is to prevent automatic HTML escaping of special characters (like +), which breaks iPXE scripts when base64-encoded content is included.
Using html/template escapes characters such as + into HTML entities (&#43;), causing malformed iPXE scripts and boot failures. Switching to text/template preserves the exact literal content required.
Manually generated iPXE scripts with base64-encoded strings using both html/template and text/template.
The text/template output preserves literal + characters:
While html/template produces escaped output:
```
#!ipxe
dhcp
set secret-base64 H4sIAAAAA&#43;//////==&#43;/
boot
```
Using text/template:
```
#!ipxe
dhcp
set …
```
=> fix: use text/template instead of html/template in auto.go to prevent HTML escaping
