tinkerbell/smee

dhcp.go
http.go
installers/coreos/ignition.go
installers/coreos/oem.go
installers/http.go
installers/vmware/kickstart-esxi.go
job/dhcp.go
main.go
metrics/setup.go
packet/endpoints.go
tftp.go

This adds some basic prometheus metrics to give a better insight into what all boots is doing.

Add prometheus metrics

---

installers/osie/main.go
installers/osie/mirror.go

part of https://github.com/tinkerbell/tink/pull/170

osie: drop elasticsearch

---

go.mod
go.sum

This includes the update to talk to cacher directly.

update cacher client package

---

packet/models.go
packet/models_cacher.go
packet/models_tinkerbell.go
packet/util.go

Minor fixes to packet/ lib that I did while working on the (defunct) cacher2tink (PR #99).

Minor changes to packet lib

---

.github/workflows/ci-non-go.sh
.github/workflows/ci.yaml
README.md
ipxe/ipxe/build.sh
shell.nix

Replace golangci-lint-action with golangci-lint from nixpkgs.
Ultimate fix for the golangci-lint-action errors messing with CI. Continuation of https://github.com/tinkerbell/boots/pull/100

Better formatting and linting

---

installers/osie/ipxe_script_test.go
installers/osie/main.go

This is for DiscoveryOS mode, a new mode of OSIE that offers various
tools to auto-detect and setup hardware during initial rack enrollment
of a server.

Add discover bootScript

---

.github/workflows/ci-non-go.sh
shell.nix

Add nixfmt to the fmt'ing bits of CI.

Ensure shell.nix is well formatted

---

http.go
job/events_test.go
job/job.go
job/job_test.go
packet/client.go
packet/endpoints_test.go
tftp.go

Start of the work to refactor `CreateFrom` for `IP` & `RemoteAddr`
Working on clean up as well as events
Local testing
No user impact as no one is using this that I am aware of
I have:

Start of refactoring of CreateFrom

---

SUPPORT.md

chore: update support location to Equinix Metal Slack

---

docs/IPXE.md

This helps to increase the understanding of the features we enable in our IPXE builds.
Just a start.
More breakdowns by arch to follow.
Fixes: #
I have:

Add doc on custom IPXE features:

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Update non code files to be uniformish amongst all repos.
Ensures our repos are all licensed correctly and contain similar/minimum
contribution info files.

Add/update DCO, CoC, contributing ... files

---

.github/workflows/ci.yaml
.golangci.yaml

This allows us to start enabling different linters.
Fixes: #
I have:

Add golangci-lint config:

---

.github/workflows/ci.yaml
.mergify.yml
.tours/dhcp-request.tour
CONTRIBUTING.md
README.md
deploy/stack/.env

Update all refs from master -> main

Prepare for default branch rename

---

installers/coreos/ipxe_script_test.go
installers/custom_ipxe/ipxe_script_test.go
installers/nixos/ipxe_script_test.go
installers/osie/ipxe_script_test.go
installers/rancher/ipxe_script_test.go
job/ipxe.go

This is a low hanging fix, long overdue. Pointed out by @rgl in #149, post merge.

Drop Packet.net from ipxe script

---

go.mod
go.sum

update ipxedust with new ipxe binaries

---

README.md

This is an Equinix Metal specific stability level and doesn't seem appropiate for a CNCF project. Also, Boots has been running in Production at Equinix Metal for quite some time.
Fixes: #
I have:

Remove the Experimental stability level:

---

Makefile

The code to accomplish these targets have been removed.
Fixes: #
I have:

Remove deprecated targets:

---

.gitignore
client/kubernetes/hardware_finder.go
cmd/boots/main.go
cmd/boots/main_test.go

Add Kubernetes namespace override. See https://github.com/tinkerbell/hegel/pull/106 for more details.

Add Kubernetes namespace override flag

---

.github/workflows/ci.yaml
rules.mk

Fixes https://github.com/tinkerbell/boots/issues/274.

Stop building 32b flavors

---

go.mod
go.sum

This version includes fixes for VLAN tagging support.
Fixes: #
I have:

Update ipxedust version:

---

cmd/boots/main.go

Otherwise we panic on the first DHCP request.

Return a nice error when DATA_MODEL_VERSION not set

---

cmd/boots/main.go

Fix a small doc comment typo
N/A
N/A
I have:

Fix doc comment typo

---

syslog/receiver.go

syslog messages are outputted as strings. This makes it very difficult to read. This PR dramatically improves the readability
of the logs sent via syslog by transforming them to structured logs.
current: 
```json
{
"level": "info",
"ts": 1675554915.0473623,
"caller": "syslog/receiver.go:187",
"msg": "host=192.168.2.143 facility=daemon severity=ERR app-name=d43ace96a835 procid=775 msg=\"{\\\"level\\\":\\\"info\\\",\\\"ts\\\":1675554913.7030935,\\\"caller\\\":\\\"worker/worker.go:445\\\",\\\"msg\\\":\\\"reporting Action Status\\\",\\\"service\\\":\\\"github.com/tinkerbell/tink\\\",\\\"workerID\\\":\\\"52:54:00:ee:0d:0b\\\",\\\"workflowID\\\":\\\"demo-wf\\\",\\\"actionName\\\":\\\"write-netplan\\\",\\\"taskName\\\":\\\"os-installation\\\",\\\"workflowID\\\":\\\"demo-wf\\\",\\\"workerID\\\":\\ …
```

Parse syslog into structured logging:

---

README.md

Add a note on the repo used to be called Boots.
Fixes: #
I have:

Add note on Boots name:

---

internal/backend/kube/kube.go

smee: toDHCPData() from CRD's TimeServers to DHCP NTPServers

smee: toDHCPData() from CRD's TimeServers to DHCP NTPServers

---

internal/backend/kube/kube.go
internal/backend/kube/kube_test.go

Facility was previously always an empty string.
Fixes: #
I have:

Get facility code from HW object:

---

.github/workflows/ci.yaml
go.mod

Add `toolchain` to go.mod and update CI. Amongst other reasons this is need so that dependabot PR's won't fail.
Fixes: #
I have:

Gotoolchain

---

go.mod

Add full go version to go.mod. Also needed for dependabot PRs to be successful.
Fixes: #
I have:

Add full go version to go.mod

---

README.md
go.mod
go.sum
internal/iso/iso.go

Readme update and tidying

---

docs/ISO-Static-IPAM.md

This describes the spec for passing data.
Fixes: #
I have:

Add doc on ISO static ipam:
